security:
  oauth2:
    client:
      registration:
        kakao:  # 카카오 로그인 설정
          client-id: 52af8ddc996fc091a26de96bfcf32f71  # 앱키 (REST API 키)
          client-secret: 4w4Thc3jCYolKkwq4Hg4LvahzcnYNWH8
          client-authentication-method: client_secret_post
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8080/login/oauth2/code/kakao
          client-name: Kakao
      provider:
        kakao:  # 카카오 OAuth2 제공자 설정
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id  # 카카오에서 사용자 식별자로 사용할 속성

jwt:
  secret: my-secret-key-study-springboot-psbsbb
  access-token-expiration: 3600000       # 1시간 (1 * 60 * 60 * 1000)
  refresh-token-expiration: 1209600000   # 14일 (14 * 24 * 60 * 60 * 1000)
